---
title: "Analysis of COVID-19 source of infection"
author: "Wenqing Cao"
date: '2020-09-27'
output: html_document
bibliography: "references.bib"
tags:
- R Markdown
- plot
- regression
categories: R
---



<div id="abstract" class="section level1">
<h1>Abstract:</h1>
<p>We investigated the OpenToronto COVID-19 Cases in Toronto data. Performed data diagnostics, and results showed that the most common way cause people infected is close contact with a case in Toronto. These results are important because once we know the source of infection, we can then make move to protect people from infection.</p>
<pre class="r"><code># get package
package &lt;- show_package(&quot;64b54586-6180-4485-83eb-81e8fae3b8fe&quot;)
package</code></pre>
<pre><code>## # A tibble: 1 x 10
##   title id    topics civic_issues excerpt dataset_category num_resources formats
##   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;   &lt;chr&gt;                    &lt;int&gt; &lt;chr&gt;  
## 1 COVI… 64b5… &lt;NA&gt;   &lt;NA&gt;         &lt;NA&gt;    &lt;NA&gt;                         1 &lt;NA&gt;   
## # … with 2 more variables: refresh_rate &lt;chr&gt;, last_refreshed &lt;date&gt;</code></pre>
<pre class="r"><code># get all resources for this package
resources &lt;- list_package_resources(&quot;64b54586-6180-4485-83eb-81e8fae3b8fe&quot;)

# identify datastore resources; by default, Toronto Open Data sets datastore resource format to CSV for non-geospatial and GeoJSON for geospatial resources
datastore_resources &lt;- filter(resources, tolower(format) %in% c(&#39;csv&#39;, &#39;geojson&#39;))

# load the first datastore resource as a sample
covid_data &lt;- filter(datastore_resources, row_number()==1) %&gt;% get_resource()
selected_covid_data = select(covid_data, &quot;Source of Infection&quot;)
selected_covid_data</code></pre>
<pre><code>## # A tibble: 17,872 x 1
##    `Source of Infection`
##    &lt;chr&gt;                
##  1 Travel               
##  2 Travel               
##  3 Travel               
##  4 Travel               
##  5 Travel               
##  6 Travel               
##  7 Travel               
##  8 Travel               
##  9 Travel               
## 10 Travel               
## # … with 17,862 more rows</code></pre>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>While COVID-19 pandemic is still affecting people in various categories globally, it brings people atteion unprecedentedly. By examining the source of infection, we can get a better understanding of how to prevent it from the root. In Toronto, most people, almost 90%, get infected by close contacting with COVID-19 carrier. Recent research indicates that Human-to-human transmission occurs primarily through direct contact or air droplets. The higher risk of transmission is within approximately 1 meter (about 3 feet) from the infected person; however, the maximum distance is still undetermined (<span class="citation">Repici et al. (2020)</span>). However, what is the most effective way to protect spreading where people live in the same house is still undetermined.</p>
<p>In our study, we analyzed the most popular topics: COVID-19 in Toronto. We looked at core data features in OpenToronto and applied Source of Infection from that. We discovered that the most common infection source is Close Contact with a case.Except N/A, the second higher infection is by community.</p>
<p>We examined Source of Infection in the OpenToronto and found out that close contact with a case is the dominant reason cause people infected. However, we did not look at and account for other factors that could potentially affect this finding, including age, specific location, and date. Source of Infection is dominated by close contact with a case, and there were a lot of missing values which could potentially affect our model. Future work should be targeted at examining the these other than source of infection and how they cause people get infected.</p>
</div>
<div id="data-discussion" class="section level1">
<h1>Data discussion</h1>
<p>The COVID-19 Cases in Toronto was conducted to an ongoing COVID-19 outbreak, in the context of an evolving global pandemic. This data set contains demographic, geographic, and severity information for all confirmed and probable cases reported to and managed by Toronto Public Health since the first case was reported in January 2020. This includes cases that are sporadic (occurring in the community) and outbreak-associated. The data are extracted from the provincial communicable disease reporting system (iPHIS) and Toronto’s custom COVID-19 case management system (CORES) and combined for reporting. Each line summarizes information for an individual case.</p>
<p>The <code>covid_data</code> dataset is a subset of the COVID-19 Cases in Toronto under the name “data” that provides a tool for teaching survey datasets and their analysis.</p>
<p>Variables in the <code>covid_data</code> dataset and their description are listed in the table below:</p>
<pre class="r"><code>data_table &lt;- data.frame(vars = c(&quot;Age Group&quot;, &quot;Source of Infection&quot;, &quot;Currently in ICU 
&quot;,&quot;_id&quot;,&quot;Assigned_ID&quot;,&quot;Outbreak Associated&quot;,&quot;Neighbourhood Name&quot;,&quot;FSA&quot;,&quot;Classification&quot;),
                           DES = c(&quot;Age at time of illness. Age groups (in years): ≤19, 20-29, 30-39, 40-49, 50-59, 60-69, 70-79, 80-89, 90+, unknown (blank)&quot;, 
                                    &quot;The most likely way that sporadic cases acquired their COVID-19 infection.&quot;, 
                                    &quot;Cases that are currently admitted to the intensive care unit (ICU)&quot;,
                                   &quot;Unique row identifier for Open Data database&quot;,
                                   &quot;A unique ID assigned to cases by Toronto Public Health for the purposes of posting to Open Data, to allow for tracking of specific cases.&quot;,
                                   &quot;Outbreak associated cases are associated with outbreaks of COVID-19 in Toronto healthcare institutions and healthcare settings (e.g. long-term care homes, retirement homes, hospitals, etc.) and other Toronto congregate settings (such as homeless shelters).&quot;,
                                   
                                   &quot;Toronto is divided into 140 geographically distinct neighborhoods that were established to help government and community agencies with local planning by providing socio-economic data for a meaningful geographic area. Please note that client postal code information is mapped to the most up-to-date census tract (CT) and neighbourhood information available from the city. As a result, neighbourhood information is not available for those with missing postal code or when postal code could not be mapped/linked to a CT.&quot;,
                                   &quot;Forward sortation area (i.e. first three characters of postal code) based on the case&#39;s primary home address. FSA values are generated from client postal codes. One FSA can span multiple neighbourhoods.&quot;,
                                   &quot;The application of the provincial case definition to categorize the cases as confirmed or probable, according to standard criteria.&quot;))
colnames(data_table) &lt;- c(&quot;Covid_data survey variables&quot;, 
                             &quot;Description&quot;)
kable(data_table, caption=&quot;Variables in the covid_data dataset 
      and their description&quot;)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-2">Table 1: </span>Variables in the covid_data dataset
and their description</caption>
<colgroup>
<col width="5%" />
<col width="94%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Covid_data survey variables</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Age Group</td>
<td align="left">Age at time of illness. Age groups (in years): ≤19, 20-29, 30-39, 40-49, 50-59, 60-69, 70-79, 80-89, 90+, unknown (blank)</td>
</tr>
<tr class="even">
<td align="left">Source of Infection</td>
<td align="left">The most likely way that sporadic cases acquired their COVID-19 infection.</td>
</tr>
<tr class="odd">
<td align="left">Currently in ICU</td>
<td align="left">Cases that are currently admitted to the intensive care unit (ICU)</td>
</tr>
<tr class="even">
<td align="left">_id</td>
<td align="left">Unique row identifier for Open Data database</td>
</tr>
<tr class="odd">
<td align="left">Assigned_ID</td>
<td align="left">A unique ID assigned to cases by Toronto Public Health for the purposes of posting to Open Data, to allow for tracking of specific cases.</td>
</tr>
<tr class="even">
<td align="left">Outbreak Associated</td>
<td align="left">Outbreak associated cases are associated with outbreaks of COVID-19 in Toronto healthcare institutions and healthcare settings (e.g. long-term care homes, retirement homes, hospitals, etc.) and other Toronto congregate settings (such as homeless shelters).</td>
</tr>
<tr class="odd">
<td align="left">Neighbourhood Name</td>
<td align="left">Toronto is divided into 140 geographically distinct neighborhoods that were established to help government and community agencies with local planning by providing socio-economic data for a meaningful geographic area. Please note that client postal code information is mapped to the most up-to-date census tract (CT) and neighbourhood information available from the city. As a result, neighbourhood information is not available for those with missing postal code or when postal code could not be mapped/linked to a CT.</td>
</tr>
<tr class="even">
<td align="left">FSA</td>
<td align="left">Forward sortation area (i.e. first three characters of postal code) based on the case’s primary home address. FSA values are generated from client postal codes. One FSA can span multiple neighbourhoods.</td>
</tr>
<tr class="odd">
<td align="left">Classification</td>
<td align="left">The application of the provincial case definition to categorize the cases as confirmed or probable, according to standard criteria.</td>
</tr>
</tbody>
</table>
<p>Below is a graph showing the type and missing value pattern of each variable. Our main variables of interest: Source of infection.</p>
<pre class="r"><code>visdat::vis_dat(covid_data) </code></pre>
<p><img src="/post/2015-07-23-r-rmarkdown_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Below are detailed statistics on the type of each variable in the dataset as well as its missing value pattern. The below also gives some summary statistics on the dataset itself such as the number of rows, the number of columns and column type frequency.</p>
<pre class="r"><code>skimr::skim(covid_data)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-4">Table 2: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">covid_data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">17872</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">18</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">16</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Outbreak Associated</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">8</td>
<td align="right">19</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Age Group</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">14</td>
<td align="right">0</td>
<td align="right">10</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Neighbourhood Name</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">35</td>
<td align="right">0</td>
<td align="right">141</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">FSA</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">97</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Source of Infection</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">6</td>
<td align="right">25</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Classification</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">8</td>
<td align="right">9</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Episode Date</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">10</td>
<td align="right">10</td>
<td align="right">0</td>
<td align="right">217</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Reported Date</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">10</td>
<td align="right">10</td>
<td align="right">0</td>
<td align="right">212</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Client Gender</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">11</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Outcome</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Currently Hospitalized</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Currently in ICU</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Currently Intubated</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Ever Hospitalized</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Ever in ICU</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Ever Intubated</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">_id</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">152582.50</td>
<td align="right">5159.35</td>
<td align="right">143647</td>
<td align="right">148114.75</td>
<td align="right">152582.5</td>
<td align="right">157050.25</td>
<td align="right">161518</td>
<td align="left">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td align="left">Assigned_ID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">9026.35</td>
<td align="right">5248.05</td>
<td align="right">1</td>
<td align="right">4482.75</td>
<td align="right">8984.5</td>
<td align="right">13529.25</td>
<td align="right">18202</td>
<td align="left">▇▇▇▇▇</td>
</tr>
</tbody>
</table>
<pre class="r"><code>covid_data$`Source of Infection` &lt;- as.character(covid_data$`Source of Infection`)
covid_data$`Source of Infection` &lt;- as.factor(covid_data$`Source of Infection`)
levels(covid_data$`Source of Infection`)</code></pre>
<pre><code>## [1] &quot;Close contact&quot;             &quot;Community&quot;                
## [3] &quot;Healthcare&quot;                &quot;Institutional&quot;            
## [5] &quot;N/A - Outbreak associated&quot; &quot;Pending&quot;                  
## [7] &quot;Travel&quot;                    &quot;Unknown/Missing&quot;</code></pre>
<pre class="r"><code>table(covid_data$`Source of Infection`)</code></pre>
<pre><code>## 
##             Close contact                 Community                Healthcare 
##                      6419                      2471                      1142 
##             Institutional N/A - Outbreak associated                   Pending 
##                       344                      5974                        70 
##                    Travel           Unknown/Missing 
##                       830                       622</code></pre>
<pre class="r"><code>round(prop.table(table(covid_data$`Source of Infection`)), 3)</code></pre>
<pre><code>## 
##             Close contact                 Community                Healthcare 
##                     0.359                     0.138                     0.064 
##             Institutional N/A - Outbreak associated                   Pending 
##                     0.019                     0.334                     0.004 
##                    Travel           Unknown/Missing 
##                     0.046                     0.035</code></pre>
<p>35.9% of the sporadic cases acquired their COVID-19 infection in this dataset are by Close contact with a case, 33.4% of the sporadic cases acquired their COVID-19 infection in this dataset are N/A. 13.8% of the sporadic cases acquired their COVID-19 infection in this dataset are by Community. 6.4% of the sporadic cases acquired their COVID-19 infection in this dataset are by Healthcare. 4.6% of the sporadic cases acquired their COVID-19 infection in this dataset are by Travel.3.5% of the sporadic cases acquired their COVID-19 infection in this dataset are missing. 1.9% of the sporadic cases acquired their COVID-19 infection in this dataset are by Institutional. 0.4% of the sporadic cases acquired their COVID-19 infection in this dataset are pending.</p>
</div>
<div id="graph" class="section level1">
<h1>Graph</h1>
<pre class="r"><code>covid_data %&gt;% 
  ggplot(aes(x = `Source of Infection`)) +
  geom_bar(mapping = aes(x = `Source of Infection`), alpha=0.5, fill=&quot;red&quot;) + 
  labs(title=&quot;Bar plot of Infection by sources of infection&quot;) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))</code></pre>
<p><img src="/post/2015-07-23-r-rmarkdown_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="graph-discussion" class="section level1">
<h1>Graph discussion</h1>
<p>In this graph we find that the frequency distribution of source of infection differs a lot for all cases. We see that the top higher infection is by close contact with a case. Except N/A, the second higher infection is by community. From this graph we can probably guess that source of infection is different amongs different cases.</p>
</div>
<div id="discussion" class="section level1">
<h1>Discussion</h1>
<p>The most common way cause people infected is close contact with a case in Toronto. Except N/A, the second higher infection is by community. This is evident from the graph.</p>
<p>To avoid close contact with a case, there are some ways:</p>
<ol style="list-style-type: decimal">
<li><p>Once a family member has symptoms of covid, the government should encourage household members to report the situation.If the report is positive, you can get a discount in hospital and give financial support.</p></li>
<li><p>There is currently an app running by the government which collaborate with apple and google which can anonymously share the covid_19 data with each other, and the government should force everyone to download.
The non-parametric ANOVA tests shows statistically significant results. Specifically, there are significant differences among the source of infection of different cases.</p></li>
</ol>
<p>To avoid the source of infection by community, there are some ways:</p>
<ol style="list-style-type: decimal">
<li><p>Strengthen community supervision，place more alcohol disinfectants.</p></li>
<li><p>Personnel visit registration in the front desk.</p></li>
</ol>
<p>There were missing data for source of infection and they were excluded since it is hard to impute values for distribution. It only constitutes 3.5% of the dataset because we have such a large datsaet.</p>
<p>Nonetheless, because of our large sample size we are able to conclude that the most common way cause people infected is close contact with a case in Toronto.</p>
<div id="weaknesses-and-next-steps" class="section level2">
<h2>Weaknesses and next steps</h2>
<p>Observations such for Outbreak-associated cases are N/A in which we miss plenty of information and lead to biased results. There could be other sources that affect infection. Our analysis did not adjust for the confounder variables and how they affect the source of infection. Examples include, age, specific location, and date. Our next steps include looking at how these variables affect infection count and how they can affect the relationship between infection count and sources of infection.</p>
<p>Code and data supporting this analysis is available at: “<a href="https://github.com/purenb666/STA304.git" class="uri">https://github.com/purenb666/STA304.git</a>”.</p>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-repici2020coronavirus">
<p>Repici, Alessandro, Roberta Maselli, Matteo Colombo, Roberto Gabbiadini, Marco Spadaccini, Andrea Anderloni, Silvia Carrara, et al. 2020. “Coronavirus (Covid-19) Outbreak: What the Department of Endoscopy Should Know.” <em>Gastrointestinal Endoscopy</em>.</p>
</div>
</div>
</div>
